### ISSUE TITLE
how to map the action with `<leader>w`?

### ISSUE THREAD

**Issue by ayamir** [archways404/qJump#1]
Thanks for your great work in advance. I want to trigger it by using custom keymap like `<leader>w`, how to implement it?

**Comment by archways404** [comment]
Hi and thank you!

Sorry for the late response, you can do it by simply following these steps:

1. Open the Command Palette (Ctrl+Shift+P or Cmd+Shift+P on Mac).
2. Search for Preferences: Open Keyboard Shortcuts (JSON).
3. Add or modify the entry:
```json
{
  "key": "ctrl+shift+w",
  "command": "qjump.hop",
  "when": "editorTextFocus"
}
```

 OR you can do it by modifying this part the [package.json](https://github.com/archways404/qJump/blob/main/package.json):
```json
"contributes": {
  "commands": [
    {
    "command": "qjump.hop",
    "title": "qJump: Hop"
    }
  ],
  "keybindings": [
    {
    "command": "qjump.hop",
    "key": "ctrl+shift+j",
    "when": "editorTextFocus",
    "win": "ctrl+shift+j",
    "mac": "ctrl+shift+j"
    }
  ]
 },
```
